import type { UtilityTypeV1, UtilityV1 } from './types';

const REGISTRY_CA_V1: UtilityV1[] = [
  // IOUs
  {
    utilityKey: 'PGE',
    displayName: 'Pacific Gas and Electric (PG&E)',
    utilityType: 'IOU',
    type: 'IOU',
    state: 'CA',
    commodities: ['ELECTRIC', 'GAS'],
    territoryNotes: 'Northern & Central California investor-owned utility.',
    tariffAcquisitionByCommodity: { ELECTRIC: 'AUTOMATED_HTML', GAS: 'AUTOMATED_HTML' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://www.pge.com/tariffs/en.html'],
      GAS: ['https://www.pge.com/tariffs/en.html'],
    },
    tariffAcquisitionMethod: 'AUTOMATED_HTML',
    primaryTariffSourceUrls: ['https://www.pge.com/tariffs/en.html'],
    confidenceLevel: 'authoritative',
    cadence: 'daily',
    tags: ['electric', 'gas', 'iou'],
    sources: { tariffs: ['tariffLibrary:ca:v0'], programs: ['programLibrary:seed:ca:v0'] },
  },
  {
    utilityKey: 'SCE',
    displayName: 'Southern California Edison (SCE)',
    utilityType: 'IOU',
    type: 'IOU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    territoryNotes: 'Southern California investor-owned utility.',
    tariffAcquisitionByCommodity: { ELECTRIC: 'AUTOMATED_HTML' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://www.sce.com/regulatory/tariff-books'] },
    tariffAcquisitionMethod: 'AUTOMATED_HTML',
    primaryTariffSourceUrls: ['https://www.sce.com/regulatory/tariff-books'],
    confidenceLevel: 'authoritative',
    cadence: 'daily',
    tags: ['electric', 'iou'],
    sources: { tariffs: ['tariffLibrary:ca:v0'], programs: ['programLibrary:seed:ca:v0'] },
  },
  {
    utilityKey: 'SDGE',
    displayName: 'San Diego Gas & Electric (SDG&E)',
    utilityType: 'IOU',
    type: 'IOU',
    state: 'CA',
    commodities: ['ELECTRIC', 'GAS'],
    territoryNotes: 'San Diego County investor-owned utility.',
    tariffAcquisitionByCommodity: { ELECTRIC: 'AUTOMATED_JSON', GAS: 'AUTOMATED_HTML' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: [
        'https://scg-uofa-api-prd-hzczb4hja0g6dcfv.a03.azurefd.net/scg-uofa-wpubtm-prd/tariffs?bookId=ELEC&sectId=ELEC-SCHEDS&utilId=SDGE',
      ],
      GAS: ['https://tariffsprd.sdge.com/sdge/tariffs/content/?utilId=SDGE&bookId=GAS&sectId=G-SCHEDS'],
    },
    tariffAcquisitionMethod: 'AUTOMATED_JSON',
    primaryTariffSourceUrls: [
      'https://scg-uofa-api-prd-hzczb4hja0g6dcfv.a03.azurefd.net/scg-uofa-wpubtm-prd/tariffs?bookId=ELEC&sectId=ELEC-SCHEDS&utilId=SDGE',
    ],
    confidenceLevel: 'authoritative',
    cadence: 'daily',
    tags: ['electric', 'gas', 'iou'],
    sources: { tariffs: ['tariffLibrary:ca:v0'], programs: ['programLibrary:seed:ca:v0'] },
  },
  {
    utilityKey: 'SOCALGAS',
    displayName: 'SoCalGas',
    utilityType: 'IOU',
    type: 'IOU',
    state: 'CA',
    commodities: ['GAS'],
    territoryNotes: 'Southern California Gas Company (natural gas utility).',
    tariffAcquisitionByCommodity: { GAS: 'AUTOMATED_HTML' },
    primaryTariffSourceUrlsByCommodity: {
      GAS: ['https://tariffsprd.socalgas.com/scg/tariffs/content/?utilId=SCG&bookId=GAS&sectId=G-SCHEDS'],
    },
    tariffAcquisitionMethod: 'AUTOMATED_HTML',
    primaryTariffSourceUrls: ['https://tariffsprd.socalgas.com/scg/tariffs/content/?utilId=SCG&bookId=GAS&sectId=G-SCHEDS'],
    confidenceLevel: 'authoritative',
    cadence: 'daily',
    tags: ['gas', 'iou'],
    sources: { tariffs: ['tariffLibraryGas:ca:v0'], programs: ['programLibrary:seed:ca:v0'] },
  },

  // POUs / municipals
  {
    utilityKey: 'PALO_ALTO_UTILITIES',
    displayName: 'City of Palo Alto Utilities',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_PDF' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: [
        'https://www.cityofpaloalto.org/Departments/Utilities/Customer-Service/Utilities-Rates',
        'https://www.cityofpaloalto.org/files/assets/public/v/2/agendas-minutes-reports/reports/city-manager-reports-cmrs/attachments/2024-rates/electric-rates-schedule.pdf',
      ],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'pou'],
    territoryNotes: 'City of Palo Alto (electric utility).',
    tariffAcquisitionMethod: 'MANUAL_PDF',
    primaryTariffSourceUrls: [
      'https://www.cityofpaloalto.org/Departments/Utilities/Customer-Service/Utilities-Rates',
      'https://www.cityofpaloalto.org/files/assets/public/v/2/agendas-minutes-reports/reports/city-manager-reports-cmrs/attachments/2024-rates/electric-rates-schedule.pdf',
    ],
  },
  {
    utilityKey: 'ALAMEDA_MUNICIPAL_POWER',
    displayName: 'Alameda Municipal Power',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://www.alamedamp.com/157/Alameda-Municipal-Power-Rates'] },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'pou'],
    territoryNotes: 'City of Alameda (electric utility).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.alamedamp.com/157/Alameda-Municipal-Power-Rates'],
  },
  {
    utilityKey: 'SILICON_VALLEY_POWER',
    displayName: 'Silicon Valley Power',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://www.siliconvalleypower.com/businesses/rates-and-fees', 'https://www.siliconvalleypower.com/residents/rates-and-fees'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'pou'],
    territoryNotes: 'City of Santa Clara (electric utility).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.siliconvalleypower.com/businesses/rates-and-fees', 'https://www.siliconvalleypower.com/residents/rates-and-fees'],
  },
  {
    utilityKey: 'SMUD',
    displayName: 'Sacramento Municipal Utility District (SMUD)',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://www.smud.org/Rate-Information'] },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'pou'],
    territoryNotes: 'Sacramento region municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.smud.org/Rate-Information'],
  },
  {
    utilityKey: 'LADWP',
    displayName: 'Los Angeles Department of Water and Power (LADWP)',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_PDF' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://rates.ladwp.com/', 'https://www.ladwp.com/sites/default/files/documents/LADWP_Electric_Rates.pdf'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'water', 'pou'],
    territoryNotes: 'City of Los Angeles municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_PDF',
    primaryTariffSourceUrls: ['https://rates.ladwp.com/', 'https://www.ladwp.com/sites/default/files/documents/LADWP_Electric_Rates.pdf'],
  },
  {
    utilityKey: 'GLENDALE_WATER_POWER',
    displayName: 'Glendale Water & Power',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://www.glendaleca.gov/government/departments/glendale-water-and-power/rates'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'water', 'pou'],
    territoryNotes: 'City of Glendale municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.glendaleca.gov/government/departments/glendale-water-and-power/rates'],
  },
  {
    utilityKey: 'PASADENA_WATER_POWER',
    displayName: 'Pasadena Water & Power',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://pwp.cityofpasadena.net/water-and-electric-rates/', 'https://pwp.cityofpasadena.net/rate-card-archive/'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'water', 'pou'],
    territoryNotes: 'City of Pasadena municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://pwp.cityofpasadena.net/water-and-electric-rates/', 'https://pwp.cityofpasadena.net/rate-card-archive/'],
  },
  {
    utilityKey: 'ANAHEIM_PUBLIC_UTILITIES',
    displayName: 'Anaheim Public Utilities',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://www.anaheim.net/653/Electric-Utility-Rate-Schedules'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'pou'],
    territoryNotes: 'City of Anaheim municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.anaheim.net/653/Electric-Utility-Rate-Schedules'],
  },
  {
    utilityKey: 'BURBANK_WATER_POWER',
    displayName: 'Burbank Water & Power',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://burbankwaterandpower.com/approved-rates', 'https://www.burbankwaterandpower.com/electric/rates-and-charges'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'water', 'pou'],
    territoryNotes: 'City of Burbank municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://burbankwaterandpower.com/approved-rates', 'https://www.burbankwaterandpower.com/electric/rates-and-charges'],
  },
  {
    utilityKey: 'RIVERSIDE_PUBLIC_UTILITIES',
    displayName: 'Riverside Public Utilities',
    utilityType: 'POU',
    type: 'POU',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://riversideca.gov/utilities/residents/rates/electric-rules-rates'],
    },
    confidenceLevel: 'partial',
    cadence: 'manual',
    tags: ['electric', 'water', 'pou'],
    territoryNotes: 'City of Riverside municipal utility.',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://riversideca.gov/utilities/residents/rates/electric-rules-rates'],
  },

  // CCAs (generation rates; delivery remains IOU)
  {
    utilityKey: 'PENINSULA_CLEAN_ENERGY',
    displayName: 'Peninsula Clean Energy (PCE)',
    utilityType: 'CCA',
    type: 'CCA',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: {
      ELECTRIC: ['https://www.peninsulacleanenergy.com/', 'https://www.peninsulacleanenergy.com/wp-content/uploads/2025/02/PCE-Commercial-Rates-Effective-02-10-2025.pdf'],
    },
    confidenceLevel: 'stub',
    cadence: 'manual',
    tags: ['cca', 'generation_adder_only'],
    territoryNotes: 'San Mateo County CCA (generation component).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://www.peninsulacleanenergy.com/', 'https://www.peninsulacleanenergy.com/wp-content/uploads/2025/02/PCE-Commercial-Rates-Effective-02-10-2025.pdf'],
  },
  {
    utilityKey: 'SILICON_VALLEY_CLEAN_ENERGY',
    displayName: 'Silicon Valley Clean Energy (SVCE)',
    utilityType: 'CCA',
    type: 'CCA',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://svcleanenergy.org/electricity-rates/'] },
    confidenceLevel: 'stub',
    cadence: 'manual',
    tags: ['cca', 'generation_adder_only'],
    territoryNotes: 'Santa Clara County CCA (generation component).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://svcleanenergy.org/electricity-rates/'],
  },
  {
    utilityKey: 'EAST_BAY_COMMUNITY_ENERGY',
    displayName: 'East Bay Community Energy (Ava Community Energy)',
    utilityType: 'CCA',
    type: 'CCA',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://avaenergy.org/about-our-rates/'] },
    confidenceLevel: 'stub',
    cadence: 'manual',
    tags: ['cca', 'generation_adder_only'],
    territoryNotes: 'Alameda County CCA (generation component).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://avaenergy.org/about-our-rates/'],
  },
  {
    utilityKey: 'SONOMA_CLEAN_POWER',
    displayName: 'Sonoma Clean Power (SCP)',
    utilityType: 'CCA',
    type: 'CCA',
    state: 'CA',
    commodities: ['ELECTRIC'],
    tariffAcquisitionByCommodity: { ELECTRIC: 'MANUAL_LINKS' },
    primaryTariffSourceUrlsByCommodity: { ELECTRIC: ['https://sonomacleanpower.org/billing/'] },
    confidenceLevel: 'stub',
    cadence: 'manual',
    tags: ['cca', 'generation_adder_only'],
    territoryNotes: 'Sonoma/Marin region CCA (generation component).',
    tariffAcquisitionMethod: 'MANUAL_LINKS',
    primaryTariffSourceUrls: ['https://sonomacleanpower.org/billing/'],
  },
];

export function getUtilityRegistryCA(): UtilityV1[] {
  return REGISTRY_CA_V1.slice();
}

export function getUtilityByKey(key: string): UtilityV1 | null {
  const k = String(key || '').trim().toUpperCase();
  return getUtilityRegistryCA().find((u) => String(u.utilityKey).toUpperCase() === k) || null;
}

export function listUtilitiesByType(type: UtilityTypeV1): UtilityV1[] {
  return getUtilityRegistryCA().filter((u) => (u.utilityType || u.type) === type);
}

